### ISSUE TITLE
to do

### ISSUE THREAD

**Issue by LindaRodriguezSa** [limarosa29/lab2-SD#4]
- [x] frase aleatoria @augusticor 
- [x] corregir números de servidores "balanceo de carga" @augusticor 
- [x] eliminar el botón falla y sustituirlo por monitoreo. @limarosa29 
- [x]  mejorar creación de instancias @cris2014971130 
- [x] obtener la ip de la maquina virtual @cris2014971130 
- [x] los log cuando voten error @augusticor

**Comment by cris2014971130** [comment]
@limarosa29 Por favor Mati, podrías crear un prompt, para la notificación de correo.

**Comment by augusticor** [comment]
Comandos para obtener las direcciónes ip:

sudo apt-get install arp-scan
sudo arp-scan --interface=vboxnet0(interfaz de red) --localnet
arp -a (se sabe que interfaz tiene las direccion IP)
sudo arp-scan --interface=wlp3s0 --localnet
